### PR TITLE
Update environment name (copy from lfirwin)

### PR DESCRIPTION
**Pull request by mfapouw**
Separate pull request containing only the update environment name changes from lfirwin:
Optionally give an environment a name.
All credits go to lfirwin.

### CODE REVIEW

**Comment by erictrue** [comment]
Thanks very much for doing the work on this.

Fixes #21 . I'll update the README (and add it to the changelog after I merge some other stuff in).

**Comment by mfapouw** [comment]
Thanks!
I also made an attempt to change the IP and the Host of the VM.
The result works, but it is a bit hacky :) Not good enough for a pull request:
https://github.com/mfapouw/vagrant-skytap/tree/vm_network

**Comment by spazquest** [comment]
I would hold off on anything related to networks. Skytap's networking is really flexible, but that means the Vagrantfile syntax has to cover a lot of different use cases as cleanly as possible. If we add the functionality piecemeal, I'm really concerned that we'll end up with kludgy syntax and be stuck with it forever.

**Comment by spazquest** [comment]
mfapouw: Regarding the IP address, I took a look at your "vm_network" branch. If you can rework this to get the IP address from the standard network settings (instead of by adding a new property), that would be awesome.

    config.vm.network "private_network", ip: "192.168.50.4"

It's okay if the implementation is a little hacky (as long as it doesn't introduce bugs). Refactoring is easier than changing the interface. :)

**Comment by mfapouw** [comment]
Hi Eric, I guess this should be possible. 

I now apply the settings to interface #0: vm.interfaces[0].id
Might be nice to let "private_network" update #0 
And for example "public_network" update #1 or something

I have to look into the syntax of the standard network settings and how to get these settings from the config. My time to work on this is very limited, but it is on my list.

**Pull request merged**
